# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a505675d61f2ab4dc24fcab31546cc3f"
application_url = "https://aramex-shipping-extension.vercel.app"
embedded = true
name = "Armex Pickup"
handle = "narmex-pickup"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "karan-working.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-07"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://aramex-shipping-extension.vercel.app/auth/callback",
  "https://aramex-shipping-extension.vercel.app/auth/shopify/callback",
  "https://aramex-shipping-extension.vercel.app/api/auth/callback"
]

[pos]
embedded = false
